apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argoapplication2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bertiniawara/updatemanifest.git
    targetRevision: HEAD
    path: deploy/
  destination:
    server: https://kubernetes.default.svc
    namespace: my-argoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
