apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: site-web
  template:
    metadata:
      labels:
        app: site-web
    spec:
      containers:
      - name: mon-app-container
        image: emmanuel236/yoyama:latest
        ports:
        - containerPort: 80
